spring.application.name=hivehub-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:hivehub_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1232}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect