spring.application.name=hivehub-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:hivehub_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1232}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

vosk.model-path=src/main/resources/vosk-model-small-es-0.42
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Modelo de Groq para el procesado de transcripciones

groq.api-key=${GROQ_API_KEY}
groq.api-url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-20b